### ISSUE TITLE
Capitalization of method names is not preserved

### ISSUE THREAD

**Issue by joe-p** [algorandfoundation/algokit-client-generator-ts#76]
With version 2.2.4, the capitalization of method names is not preserved. 

If there is an ABI method defined with multiple capital letters in a row, such as `getRegisteredASA`, the generated typed client will have a method `getRegisteredAsa`. One would exepct capitalization to be preserved in the typed client.

**Comment by aorumbayev** [comment]
@joe-p this wasn't introduced in 2.2.4 i believe has been default behaviour since https://github.com/algorandfoundation/algokit-client-generator-ts/commit/54c952383512462164490eda32de963f698aad18. 

The method that converts method names is this line -> https://github.com/algorandfoundation/algokit-client-generator-ts/blob/b8a555e01015894e57393fb0dc214729dd997f82/src/util/sanitization.ts#L6

And as you can see it converts the text into an idiomatic camelCase because at the time of writing the generators - beaker was the main target and beaker-ts served as a reference source. Which deals with python and its all snake case, so i assume it was a safe assumption for the team to make to parse it to camelCase.

I assume in your case you are dealing with tealscript and you want support for non idiomatic camel cased method names to be preserved? Please, this is only affects the generated method not the original ABI method name so even though its changed to getRegisteredAsa it will still call the right abi endpoint in this case. 

If we were to address this I would assume some regex matching would be needed to catch such cases and only apply camel case if the value given is snake cased. Something like:

```ts
export const makeSafeMethodIdentifier = (value: string) => {
  const sanitizedValue = replaceInvalidWithUnderscore(value)

  // Check if the string already satisfies TypeScript naming conventions
  if (/^[a-z][a-zA-Z0-9]*$/.test(sanitizedValue)) {
    return sanitizedValue.charAt(0).toLowerCase() + sanitizedValue.slice(1)
  } else {
    // If it's in snake_case or doesn't satisfy TypeScript naming conventions, convert it to camelCase
    return camelCase(sanitizedValue)
  }
```

This would not affect anything on python generator repo though i assume since there we always parse everything into snake_case. 

@tristanmenzel @robdmoore what do you think about the reported issue? Should we apply extra regex matching to avoid formatting method names as @joe-p mentions or idiomatic camelCase was by design?

**Comment by joe-p** [comment]
I would also think this affects Python methods with capital letter too, no? If so, I think it would be strange to loose capitalization coming from Python as well. 

From PEP 8:

> Note: When using acronyms in CapWords, capitalize all the letters of the acronym. Thus HTTPServerError is better than HttpServerError.

**Comment by tristanmenzel** [comment]
Seems like a bit of a non-issue to me since the correct method will still be called by the client. 

We could maybe add an option to use method names verbatim with the caveat that abi methods with invalid typescript names won't work. 

As previously stated, the original intent was to convert names following a python naming convention to one that follows typescript's. Not to preserve any existing convention.

**Comment by joe-p** [comment]
I think it's mostly a matter of UX. If I write a method in my smart contract, I would expect to use that methods name to call it from the client, not another name. 

I like the solution @aorumbayev proposed where it only modifies the name if it is not already following TS conventions.

**Comment by tristanmenzel** [comment]
I believe that would be a breaking change though for existing contracts that happen to have valid names so I'd rather we did it through an option

**Comment by joe-p** [comment]
It'd only be breaking change for those using TEALScript though, no? I don't have a strong opinion against making it an option, I just think this change won't really impact any production uses.

**Comment by robdmoore** [comment]
If we don't make it an option, how would we detect we don't need to do a transformation?

lower case starting letter, and only alpha numerics (i.e. no underscores, etc.)?

Alternatively, having a by default it will create consistent names, but you can optionally tell it you like your existing naming is probably a useful feature since it gives flexibility back to the developer?
